import localFont from "next/font/local";
import "./globals.css";
import Header from "./components/SharedComponents/Header/Header";
import Footer from "./components/SharedComponents/Footer/Footer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Auction-Website",
  description: "Generated by create next app",
  icons: {
    icon: "/images/logo/Layer1.png", 
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header/ >
        {children}
        <Footer />
      </body>
    </html>
  );
}
